"""Constants for the PowerManager integration."""

DOMAIN = "powermanager"
NAME = "PowerManager"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_UNIT_ID = "unit_id"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_GRID_POWER_ENTITY = "grid_power_entity"
CONF_GRID_IMPORT_POWER_ENTITY = "grid_import_power_entity"
CONF_GRID_EXPORT_POWER_ENTITY = "grid_export_power_entity"
CONF_PV_POWER_ENTITY = "pv_power_entity"
CONF_LOAD_POWER_ENTITY = "load_power_entity"
CONF_ESTIMATE_REMAINING_LOAD = "estimate_remaining_load"
CONF_LOAD_FORECAST_HISTORY_DAYS = "load_forecast_history_days"
CONF_RULES_YAML = "rules_yaml"
CONF_TELEMETRY_MAX_AGE = "telemetry_max_age"
CONF_PRICE_ENTITY = "price_entity"
CONF_STATIC_PRICE_PER_KWH = "static_price_per_kwh"
CONF_REMAINING_PV_FORECAST_ENTITY = "remaining_pv_forecast_entity"
CONF_REMAINING_LOAD_FORECAST_ENTITY = "remaining_load_forecast_entity"

DEFAULT_PORT = 502
DEFAULT_UNIT_ID = 3
DEFAULT_SCAN_INTERVAL_SECONDS = 30
MIN_SCAN_INTERVAL_SECONDS = 5
MAX_SCAN_INTERVAL_SECONDS = 300
DEFAULT_TELEMETRY_MAX_AGE_SECONDS = 120
MIN_TELEMETRY_MAX_AGE_SECONDS = 10
MAX_TELEMETRY_MAX_AGE_SECONDS = 3600
DEFAULT_LOAD_FORECAST_HISTORY_DAYS = 7
MIN_LOAD_FORECAST_HISTORY_DAYS = 3
MAX_LOAD_FORECAST_HISTORY_DAYS = 28
